### ISSUE TITLE
Exception when running the console command

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-seeder-plugin#1]
factories.php

```php
<?php

/** @var $factory Illuminate\Database\Eloquent\Factory */
$factory->define(\Voilaah\Octovod\Models\Author::class, function (\OFFLINE\Seeder\Classes\Generator $faker) {
    return [
        'name' => $name = $faker->name,
        'slug' => str_slug($name),
    ];
});
```

Exception after running the command console `php artisan plugin:seed`

```php
[2020-08-14 10:35:56] development.ERROR: OFFLINE.Seeder failed: Unable to locate factory with name [default] [Voilaah\Octovod\Models\Author]. ["[object] (InvalidArgumentException(code: 0): Unable to locate factory with name [default] [Voilaah\\Octovod\\Models\\Author]. at /Users/christophevidal/Sites/octoflix/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php:248)\n[stacktrace]\n#0 /Users/christophevidal/Sites/octoflix/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/GuardsAttributes.php(122): Illuminate\\Database\\Eloquent\\FactoryBuilder->Illuminate\\Database\\Eloquent\\{closure}()\n#1 /Users/christophevidal/Sites/octoflix/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php(260): Illuminate\\Database\\Eloquent\\Model::unguarded(Object(Closure))\n#2 /Users/christophevidal/Sites/octoflix/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php(193): Illuminate\\Database\\Eloquent\\FactoryBuilder->makeInstance(Array)\n#3 [internal function]: Illuminate\\Database\\Eloquent\\FactoryBuilder->Illuminate\\Database\\Eloquent\\{closure}(1)\n#4 /Users/christophevidal/Sites/octoflix/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php(194): array_map(Object(Closure), Array)\n#5 /Users/christophevidal/Sites/octoflix/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php(148): Illuminate\\Database\\Eloquent\\FactoryBuilder->make(Array)\n#6 /Users/christophevidal/Sites/octoflix/plugins/voilaah/octovod/Plugin.php(17): Illuminate\\Database\\Eloquent\\FactoryBuilder->create()\n#7 /Users/christophevidal/Sites/octoflix/plugins/offline/seeder/classes/SeederManager.php(41): Voilaah\\Octovod\\Plugin->registerSeeder()\n#8 /Users/christophevidal/Sites/octoflix/vendor/laravel/framework/src/Illuminate/Support/Collection.php(339): OFFLINE\\Seeder\\Classes\\SeederManager->OFFLINE\\Seeder\\Classes\\{closure}(Object(Voilaah\\Octovod\\Plugin), 'Voilaah.Octovod')\n#9 /Users/christophevidal/Sites/octoflix/plugins/offline/seeder/classes/SeederManager.php(54): Illuminate\\Support\\Collection->each(Object(Closure))\n#10 /Users/christophevidal/Sites/octoflix/plugins/offline/seeder/console/PluginSeedCommand.php(20): OFFLINE\\Seeder\\Classes\\SeederManager->seed(false, Object(Illuminate\\Console\\OutputStyle))\n#11 [internal function]: OFFLINE\\Seeder\\Console\\PluginSeedCommand->handle()\n#12 /Users/christophevidal/Sites/octoflix/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)\n#13 /Users/christophevidal/Sites/octoflix/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()\n#14 /Users/christophevidal/Sites/octoflix/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(October\\Rain\\Foundation\\Application), Array, Object(Closure))\n#15 /Users/christophevidal/Sites/octoflix/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(October\\Rain\\Foundation\\Application), Array, Array, NULL)\n#16 /Users/christophevidal/Sites/octoflix/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)\n#17 /Users/christophevidal/Sites/octoflix/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))\n#18 /Users/christophevidal/Sites/octoflix/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))\n#19 /Users/christophevidal/Sites/octoflix/vendor/symfony/console/Application.php(987): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#20 /Users/christophevidal/Sites/octoflix/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand(Object(OFFLINE\\Seeder\\Console\\PluginSeedCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#21 /Users/christophevidal/Sites/octoflix/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#22 /Users/christophevidal/Sites/octoflix/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#23 /Users/christophevidal/Sites/octoflix/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#24 /Users/christophevidal/Sites/octoflix/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#25 {main}\n"] 

```

**Comment by chrisvidal** [comment]
Hmmm I dont see any plugin updates?

**Comment by chkilel** [comment]
You can change it manualy,  I made a PR for this, it's not yet merged from OFFLINE-GmbH.

**Comment by tobias-kuendig** [comment]
This issue seems to be fixed, thanks guys.
